// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzHp0jaeLbbPZC837J7IHdMMvunPbZhcI',
    appId: '1:71474180101:web:9585d0ff1d8d8ab0b96c6c',
    messagingSenderId: '71474180101',
    projectId: 'maxiruby',
    authDomain: 'maxiruby.firebaseapp.com',
    storageBucket: 'maxiruby.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1vVAmBjHGien44yUYBbrqPKoWxluhJFE',
    appId: '1:71474180101:android:50ac17ef8270959bb96c6c',
    messagingSenderId: '71474180101',
    projectId: 'maxiruby',
    storageBucket: 'maxiruby.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWHsFUSwpEgAQvZhuoH1mVSxFy7r61UQ',
    appId: '1:71474180101:ios:3276e9fbafeec54cb96c6c',
    messagingSenderId: '71474180101',
    projectId: 'maxiruby',
    storageBucket: 'maxiruby.appspot.com',
    iosBundleId: 'com.rvyazilim.maxiruby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYWHsFUSwpEgAQvZhuoH1mVSxFy7r61UQ',
    appId: '1:71474180101:ios:5042e318e25a1708b96c6c',
    messagingSenderId: '71474180101',
    projectId: 'maxiruby',
    storageBucket: 'maxiruby.appspot.com',
    iosBundleId: 'com.example.maxiruby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzHp0jaeLbbPZC837J7IHdMMvunPbZhcI',
    appId: '1:71474180101:web:5e81639b01faaa94b96c6c',
    messagingSenderId: '71474180101',
    projectId: 'maxiruby',
    authDomain: 'maxiruby.firebaseapp.com',
    storageBucket: 'maxiruby.appspot.com',
  );
}
